routes/web.php
    Route::get('/course/{course_id}/delete-chapter/{chapter_id}', 'ManageCourseController@deleteChapter');
    Route::post('/course/{course_id}/chapter-elements-order-update/{chapter_id}', 'ManageCourseController@chapterElementsOrderUpdate');
    Route::get('/course/{course_id}/chapter-order-edit', 'ManageCourseController@chapterOrderEdit');
    Route::post('/course/{course_id}/chapter-order-edit-update', 'ManageCourseController@chapterOrderEditUpdate');

    Route::get('/add-element/{course_id}/{chapter_id}', 'ManageChapterItemsController@addElement');
    Route::post('/add-element-store/{course_id}/{chapter_id}', 'ManageChapterItemsController@addElementStore');
    Route::get('/edit-element/{element_id}/{item_id}', 'ManageChapterItemsController@editElement');

    Route::get('/course/{course_id}/edit-element/{element_id}', 'ManageChapterItemsController@editElement');
    Route::post('/course/{course_id}/change-elem-name-update/{element_id}', 'ManageChapterItemsController@changeElemName');
    Route::get('/course/{course_id}/delete-element/{element_id}', 'ManageChapterItemsController@deleteElement');

    Route::post('/course/{course_id}/edit-video-update/{chapter_item_id}', 'ManageChapterItemsController@editVideoUpdate');
    Route::post('/course/{course_id}/add-file-store/{chapter_item_id}', 'ManageChapterItemsController@addFileStore');
    Route::get('/course/{course_id}/delete-file/{file_id}', 'ManageChapterItemsController@deleteFile');
    Route::post('/course/{course_id}/edit-page-update/{chapter_item_id}', 'ManageChapterItemsController@editPageUpdate');
    Route::post('/upload-page-media/ckeditor', 'ManageChapterItemsController@uploadCkeditorMedia')->name('upload-ckeditor-media');

    Route::get('/course/{course_id}/test/{test_id}/add-question-store', 'ManageChapterItemsController@addQuestionStore');
    Route::get('/course/{course_id}/delete-question/{question_id}', 'ManageChapterItemsController@deleteQuestion');
    Route::get('/course/{course_id}/question/{question_id}/add-answer-store', 'ManageChapterItemsController@addAnswerStore');
    Route::get('/course/{course_id}/question/{question_id}/delete-answer/{answer_id}', 'ManageChapterItemsController@deleteAnswer');
    Route::post('/course/{course}/edit-question-update/{question_id}', 'ManageChapterItemsController@editQuestionUpdate');

});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/media', 'UsersController@storeMedia')->name('users.storeMedia');
    Route::post('users/ckmedia', 'UsersController@storeCKEditorImages')->name('users.storeCKEditorImages');
    Route::resource('users', 'UsersController');

    // Course Elements
    Route::delete('course-elements/destroy', 'CourseElementsController@massDestroy')->name('course-elements.massDestroy');
    Route::post('course-elements/media', 'CourseElementsController@storeMedia')->name('course-elements.storeMedia');
    Route::post('course-elements/ckmedia', 'CourseElementsController@storeCKEditorImages')->name('course-elements.storeCKEditorImages');
    Route::resource('course-elements', 'CourseElementsController');

    // Course Category
    Route::delete('course-categories/destroy', 'CourseCategoryController@massDestroy')->name('course-categories.massDestroy');
    Route::resource('course-categories', 'CourseCategoryController');

    // Course Class
    Route::delete('course-classes/destroy', 'CourseClassController@massDestroy')->name('course-classes.massDestroy');
    Route::resource('course-classes', 'CourseClassController');

    // Game Background
    Route::delete('game-backgrounds/destroy', 'GameBackgroundController@massDestroy')->name('game-backgrounds.massDestroy');
    Route::post('game-backgrounds/media', 'GameBackgroundController@storeMedia')->name('game-backgrounds.storeMedia');
    Route::post('game-backgrounds/ckmedia', 'GameBackgroundController@storeCKEditorImages')->name('game-backgrounds.storeCKEditorImages');
    Route::resource('game-backgrounds', 'GameBackgroundController');

    // Station
    Route::delete('stations/destroy', 'StationController@massDestroy')->name('stations.massDestroy');
    Route::post('stations/media', 'StationController@storeMedia')->name('stations.storeMedia');
    Route::post('stations/ckmedia', 'StationController@storeCKEditorImages')->name('stations.storeCKEditorImages');
    Route::resource('stations', 'StationController');

    // Sign
    Route::delete('signs/destroy', 'SignController@massDestroy')->name('signs.massDestroy');
    Route::post('signs/media', 'SignController@storeMedia')->name('signs.storeMedia');
    Route::post('signs/ckmedia', 'SignController@storeCKEditorImages')->name('signs.storeCKEditorImages');
    Route::resource('signs', 'SignController');

    // Color
    Route::delete('colors/destroy', 'ColorController@massDestroy')->name('colors.massDestroy');
    Route::resource('colors', 'ColorController');

    // Course
    Route::delete('courses/destroy', 'CourseController@massDestroy')->name('courses.massDestroy');
    Route::post('courses/media', 'CourseController@storeMedia')->name('courses.storeMedia');
    Route::post('courses/ckmedia', 'CourseController@storeCKEditorImages')->name('courses.storeCKEditorImages');
    Route::resource('courses', 'CourseController');

    // Course Chapter
    Route::delete('course-chapters/destroy', 'CourseChapterController@massDestroy')->name('course-chapters.massDestroy');
    Route::resource('course-chapters', 'CourseChapterController');

    // Chapter Item
    Route::delete('chapter-items/destroy', 'ChapterItemController@massDestroy')->name('chapter-items.massDestroy');
    Route::resource('chapter-items', 'ChapterItemController');

    // Video
    Route::delete('videos/destroy', 'VideoController@massDestroy')->name('videos.massDestroy');
    Route::post('videos/media', 'VideoController@storeMedia')->name('videos.storeMedia');
    Route::post('videos/ckmedia', 'VideoController@storeCKEditorImages')->name('videos.storeCKEditorImages');
    Route::resource('videos', 'VideoController');

    // File
    Route::delete('files/destroy', 'FileController@massDestroy')->name('files.massDestroy');
    Route::post('files/media', 'FileController@storeMedia')->name('files.storeMedia');
    Route::post('files/ckmedia', 'FileController@storeCKEditorImages')->name('files.storeCKEditorImages');
    Route::resource('files', 'FileController');

    // Page
    Route::delete('pages/destroy', 'PageController@massDestroy')->name('pages.massDestroy');
    Route::post('pages/media', 'PageController@storeMedia')->name('pages.storeMedia');
    Route::post('pages/ckmedia', 'PageController@storeCKEditorImages')->name('pages.storeCKEditorImages');
    Route::resource('pages', 'PageController');

    // Test
    Route::delete('tests/destroy', 'TestController@massDestroy')->name('tests.massDestroy');
    Route::post('tests/media', 'TestController@storeMedia')->name('tests.storeMedia');
    Route::post('tests/ckmedia', 'TestController@storeCKEditorImages')->name('tests.storeCKEditorImages');
    Route::resource('tests', 'TestController');

    // Question
    Route::delete('questions/destroy', 'QuestionController@massDestroy')->name('questions.massDestroy');
    Route::post('questions/media', 'QuestionController@storeMedia')->name('questions.storeMedia');
    Route::post('questions/ckmedia', 'QuestionController@storeCKEditorImages')->name('questions.storeCKEditorImages');
    Route::resource('questions', 'QuestionController');

    // Answer
    Route::delete('answers/destroy', 'AnswerController@massDestroy')->name('answers.massDestroy');
    Route::resource('answers', 'AnswerController');

    // News
    Route::delete('news/destroy', 'NewsController@massDestroy')->name('news.massDestroy');
    Route::post('news/media', 'NewsController@storeMedia')->name('news.storeMedia');
    Route::post('news/ckmedia', 'NewsController@storeCKEditorImages')->name('news.storeCKEditorImages');
    Route::resource('news', 'NewsController');

    // Popup News
    Route::delete('popup-news/destroy', 'PopupNewsController@massDestroy')->name('popup-news.massDestroy');
    Route::resource('popup-news', 'PopupNewsController');

    // Game Available Items
    Route::delete('game-available-items/destroy', 'GameAvailableItemsController@massDestroy')->name('game-available-items.massDestroy');
    Route::resource('game-available-items', 'GameAvailableItemsController');

    // Passed Test
    Route::delete('passed-tests/destroy', 'PassedTestController@massDestroy')->name('passed-tests.massDestroy');
    Route::resource('passed-tests', 'PassedTestController');

    // Test Sign Color
    Route::delete('test-sign-colors/destroy', 'TestSignColorController@massDestroy')->name('test-sign-colors.massDestroy');
    Route::resource('test-sign-colors', 'TestSignColorController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');

app/Models/GameBackground.php
<?php

namespace App\Models;

use \DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class GameBackground extends Model implements HasMedia
{
    use SoftDeletes;
    use InteractsWithMedia;
    use HasFactory;

    public $table = 'game_backgrounds';

    protected $appends = [
        'image',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'ritm_price',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('thumb')->fit('crop', 50, 50);
        $this->addMediaConversion('preview')->fit('crop', 120, 120);
    }

    public function getImageAttribute()
    {
        $file = $this->getMedia('image')->last();
        if ($file) {
            $file->url       = $file->getUrl();
            $file->thumbnail = $file->getUrl('thumb');
            $file->preview   = $file->getUrl('preview');
        }

        return $file;
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/GameBackgroundController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\MassDestroyGameBackgroundRequest;
use App\Http\Requests\StoreGameBackgroundRequest;
use App\Http\Requests\UpdateGameBackgroundRequest;
use App\Models\GameBackground;
use Gate;
use Illuminate\Http\Request;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use Symfony\Component\HttpFoundation\Response;

class GameBackgroundController extends Controller
{
    use MediaUploadingTrait;

    public function index()
    {
        abort_if(Gate::denies('game_background_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $gameBackgrounds = GameBackground::with(['media'])->get();

        return view('admin.gameBackgrounds.index', compact('gameBackgrounds'));
    }

    public function create()
    {
        abort_if(Gate::denies('game_background_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.gameBackgrounds.create');
    }

    public function store(StoreGameBackgroundRequest $request)
    {
        $gameBackground = GameBackground::create($request->all());

        if ($request->input('image', false)) {
            $gameBackground->addMedia(storage_path('tmp/uploads/' . basename($request->input('image'))))->toMediaCollection('image');
        }

        if ($media = $request->input('ck-media', false)) {
            Media::whereIn('id', $media)->update(['model_id' => $gameBackground->id]);
        }

        return redirect()->route('admin.game-backgrounds.index');
    }

    public function edit(GameBackground $gameBackground)
    {
        abort_if(Gate::denies('game_background_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.gameBackgrounds.edit', compact('gameBackground'));
    }

    public function update(UpdateGameBackgroundRequest $request, GameBackground $gameBackground)
    {
        $gameBackground->update($request->all());

        if ($request->input('image', false)) {
            if (!$gameBackground->image || $request->input('image') !== $gameBackground->image->file_name) {
                if ($gameBackground->image) {
                    $gameBackground->image->delete();
                }
                $gameBackground->addMedia(storage_path('tmp/uploads/' . basename($request->input('image'))))->toMediaCollection('image');
            }
        } elseif ($gameBackground->image) {
            $gameBackground->image->delete();
        }

        return redirect()->route('admin.game-backgrounds.index');
    }

    public function show(GameBackground $gameBackground)
    {
        abort_if(Gate::denies('game_background_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.gameBackgrounds.show', compact('gameBackground'));
    }

    public function destroy(GameBackground $gameBackground)
    {
        abort_if(Gate::denies('game_background_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $gameBackground->delete();

        return back();
    }

    public function massDestroy(MassDestroyGameBackgroundRequest $request)
    {
        GameBackground::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }

    public function storeCKEditorImages(Request $request)
    {
        abort_if(Gate::denies('game_background_create') && Gate::denies('game_background_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $model         = new GameBackground();
        $model->id     = $request->input('crud_id', 0);
        $model->exists = true;
        $media         = $model->addMediaFromRequest('upload')->toMediaCollection('ck-media');

        return response()->json(['id' => $media->id, 'url' => $media->getUrl()], Response::HTTP_CREATED);
    }
}

resources/views/admin/gameBackgrounds/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.gameBackground.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.game-backgrounds.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.gameBackground.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.gameBackground.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="image">{{ trans('cruds.gameBackground.fields.image') }}</label>
                <div class="needsclick dropzone {{ $errors->has('image') ? 'is-invalid' : '' }}" id="image-dropzone">
                </div>
                @if($errors->has('image'))
                    <div class="invalid-feedback">
                        {{ $errors->first('image') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.gameBackground.fields.image_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="ritm_price">{{ trans('cruds.gameBackground.fields.ritm_price') }}</label>
                <input class="form-control {{ $errors->has('ritm_price') ? 'is-invalid' : '' }}" type="number" name="ritm_price" id="ritm_price" value="{{ old('ritm_price', '0') }}" step="1" required>
                @if($errors->has('ritm_price'))
                    <div class="invalid-feedback">
                        {{ $errors->first('ritm_price') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.gameBackground.fields.ritm_price_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    Dropzone.options.imageDropzone = {
    url: '{{ route('admin.game-backgrounds.storeMedia') }}',
    maxFilesize: 30, // MB
    acceptedFiles: '.jpeg,.jpg,.png,.gif',
    maxFiles: 1,
    addRemoveLinks: true,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    params: {
      size: 30,
      width: 6000,
      height: 6000
    },
    success: function (file, response) {
      $('form').find('input[name="image"]').remove()
      $('form').append('<input type="hidden" name="image" value="' + response.name + '">')
    },
    removedfile: function (file) {
      file.previewElement.remove()
      if (file.status !== 'error') {
        $('form').find('input[name="image"]').remove()
        this.options.maxFiles = this.options.maxFiles + 1
      }
    },
    init: function () {
@if(isset($gameBackground) && $gameBackground->image)
      var file = {!! json_encode($gameBackground->image) !!}
          this.options.addedfile.call(this, file)
      this.options.thumbnail.call(this, file, file.preview)
      file.previewElement.classList.add('dz-complete')
      $('form').append('<input type="hidden" name="image" value="' + file.file_name + '">')
      this.options.maxFiles = this.options.maxFiles - 1
@endif
    },
    error: function (file, response) {
        if ($.type(response) === 'string') {
            var message = response //dropzone sends it's own error messages in string
        } else {
            var message = response.errors.file
        }
        file.previewElement.classList.add('dz-error')
        _ref = file.previewElement.querySelectorAll('[data-dz-errormessage]')
        _results = []
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            node = _ref[_i]
            _results.push(node.textContent = message)
        }

        return _results
    }
}
</script>
@endsection

resources/views/admin/gameBackgrounds/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.gameBackground.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.game-backgrounds.update", [$gameBackground->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.gameBackground.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $gameBackground->name) }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.gameBackground.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="image">{{ trans('cruds.gameBackground.fields.image') }}</label>
                <div class="needsclick dropzone {{ $errors->has('image') ? 'is-invalid' : '' }}" id="image-dropzone">
                </div>
                @if($errors->has('image'))
                    <div class="invalid-feedback">
                        {{ $errors->first('image') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.gameBackground.fields.image_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="ritm_price">{{ trans('cruds.gameBackground.fields.ritm_price') }}</label>
                <input class="form-control {{ $errors->has('ritm_price') ? 'is-invalid' : '' }}" type="number" name="ritm_price" id="ritm_price" value="{{ old('ritm_price', $gameBackground->ritm_price) }}" step="1" required>
                @if($errors->has('ritm_price'))
                    <div class="invalid-feedback">
                        {{ $errors->first('ritm_price') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.gameBackground.fields.ritm_price_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    Dropzone.options.imageDropzone = {
    url: '{{ route('admin.game-backgrounds.storeMedia') }}',
    maxFilesize: 30, // MB
    acceptedFiles: '.jpeg,.jpg,.png,.gif',
    maxFiles: 1,
    addRemoveLinks: true,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    params: {
      size: 30,
      width: 6000,
      height: 6000
    },
    success: function (file, response) {
      $('form').find('input[name="image"]').remove()
      $('form').append('<input type="hidden" name="image" value="' + response.name + '">')
    },
    removedfile: function (file) {
      file.previewElement.remove()
      if (file.status !== 'error') {
        $('form').find('input[name="image"]').remove()
        this.options.maxFiles = this.options.maxFiles + 1
      }
    },
    init: function () {
@if(isset($gameBackground) && $gameBackground->image)
      var file = {!! json_encode($gameBackground->image) !!}
          this.options.addedfile.call(this, file)
      this.options.thumbnail.call(this, file, file.preview)
      file.previewElement.classList.add('dz-complete')
      $('form').append('<input type="hidden" name="image" value="' + file.file_name + '">')
      this.options.maxFiles = this.options.maxFiles - 1
@endif
    },
    error: function (file, response) {
        if ($.type(response) === 'string') {
            var message = response //dropzone sends it's own error messages in string
        } else {
            var message = response.errors.file
        }
        file.previewElement.classList.add('dz-error')
        _ref = file.previewElement.querySelectorAll('[data-dz-errormessage]')
        _results = []
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            node = _ref[_i]
            _results.push(node.textContent = message)
        }

        return _results
    }
}
</script>
@endsection

resources/views/admin/gameBackgrounds/index.blade.php
@extends('layouts.admin')
@section('content')
@can('game_background_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.game-backgrounds.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.gameBackground.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.gameBackground.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-GameBackground">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.gameBackground.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.gameBackground.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.gameBackground.fields.image') }}
                        </th>
                        <th>
                            {{ trans('cruds.gameBackground.fields.ritm_price') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($gameBackgrounds as $key => $gameBackground)
                        <tr data-entry-id="{{ $gameBackground->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $gameBackground->id ?? '' }}
                            </td>
                            <td>
                                {{ $gameBackground->name ?? '' }}
                            </td>
                            <td>
                                @if($gameBackground->image)
                                    <a href="{{ $gameBackground->image->getUrl() }}" target="_blank" style="display: inline-block">
                                        <img src="{{ $gameBackground->image->getUrl('thumb') }}">
                                    </a>
                                @endif
                            </td>
                            <td>
                                {{ $gameBackground->ritm_price ?? '' }}
                            </td>
                            <td>
                                @can('game_background_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.game-backgrounds.show', $gameBackground->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('game_background_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.game-backgrounds.edit', $gameBackground->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('game_background_delete')
                                    <form action="{{ route('admin.game-backgrounds.destroy', $gameBackground->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('game_background_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.game-backgrounds.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-GameBackground:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection