routes/web.php
    Route::get('/course/{course_id}/delete-chapter/{chapter_id}', 'ManageCourseController@deleteChapter');
    Route::post('/course/{course_id}/chapter-elements-order-update/{chapter_id}', 'ManageCourseController@chapterElementsOrderUpdate');
    Route::get('/course/{course_id}/chapter-order-edit', 'ManageCourseController@chapterOrderEdit');
    Route::post('/course/{course_id}/chapter-order-edit-update', 'ManageCourseController@chapterOrderEditUpdate');

    Route::get('/add-element/{course_id}/{chapter_id}', 'ManageChapterItemsController@addElement');
    Route::post('/add-element-store/{course_id}/{chapter_id}', 'ManageChapterItemsController@addElementStore');
    Route::get('/edit-element/{element_id}/{item_id}', 'ManageChapterItemsController@editElement');

    Route::get('/course/{course_id}/edit-element/{element_id}', 'ManageChapterItemsController@editElement');
    Route::post('/course/{course_id}/change-elem-name-update/{element_id}', 'ManageChapterItemsController@changeElemName');
    Route::get('/course/{course_id}/delete-element/{element_id}', 'ManageChapterItemsController@deleteElement');

    Route::post('/course/{course_id}/edit-video-update/{chapter_item_id}', 'ManageChapterItemsController@editVideoUpdate');
    Route::post('/course/{course_id}/add-file-store/{chapter_item_id}', 'ManageChapterItemsController@addFileStore');
    Route::get('/course/{course_id}/delete-file/{file_id}', 'ManageChapterItemsController@deleteFile');
    Route::post('/course/{course_id}/edit-page-update/{chapter_item_id}', 'ManageChapterItemsController@editPageUpdate');
    Route::post('/upload-page-media/ckeditor', 'ManageChapterItemsController@uploadCkeditorMedia')->name('upload-ckeditor-media');

    Route::get('/course/{course_id}/test/{test_id}/add-question-store', 'ManageChapterItemsController@addQuestionStore');
    Route::get('/course/{course_id}/delete-question/{question_id}', 'ManageChapterItemsController@deleteQuestion');
    Route::get('/course/{course_id}/question/{question_id}/add-answer-store', 'ManageChapterItemsController@addAnswerStore');
    Route::get('/course/{course_id}/question/{question_id}/delete-answer/{answer_id}', 'ManageChapterItemsController@deleteAnswer');
    Route::post('/course/{course}/edit-question-update/{question_id}', 'ManageChapterItemsController@editQuestionUpdate');

});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/media', 'UsersController@storeMedia')->name('users.storeMedia');
    Route::post('users/ckmedia', 'UsersController@storeCKEditorImages')->name('users.storeCKEditorImages');
    Route::resource('users', 'UsersController');

    // Course Elements
    Route::delete('course-elements/destroy', 'CourseElementsController@massDestroy')->name('course-elements.massDestroy');
    Route::post('course-elements/media', 'CourseElementsController@storeMedia')->name('course-elements.storeMedia');
    Route::post('course-elements/ckmedia', 'CourseElementsController@storeCKEditorImages')->name('course-elements.storeCKEditorImages');
    Route::resource('course-elements', 'CourseElementsController');

    // Course Category
    Route::delete('course-categories/destroy', 'CourseCategoryController@massDestroy')->name('course-categories.massDestroy');
    Route::resource('course-categories', 'CourseCategoryController');

    // Course Class
    Route::delete('course-classes/destroy', 'CourseClassController@massDestroy')->name('course-classes.massDestroy');
    Route::resource('course-classes', 'CourseClassController');

    // Game Background
    Route::delete('game-backgrounds/destroy', 'GameBackgroundController@massDestroy')->name('game-backgrounds.massDestroy');
    Route::post('game-backgrounds/media', 'GameBackgroundController@storeMedia')->name('game-backgrounds.storeMedia');
    Route::post('game-backgrounds/ckmedia', 'GameBackgroundController@storeCKEditorImages')->name('game-backgrounds.storeCKEditorImages');
    Route::resource('game-backgrounds', 'GameBackgroundController');

    // Station
    Route::delete('stations/destroy', 'StationController@massDestroy')->name('stations.massDestroy');
    Route::post('stations/media', 'StationController@storeMedia')->name('stations.storeMedia');
    Route::post('stations/ckmedia', 'StationController@storeCKEditorImages')->name('stations.storeCKEditorImages');
    Route::resource('stations', 'StationController');

    // Sign
    Route::delete('signs/destroy', 'SignController@massDestroy')->name('signs.massDestroy');
    Route::post('signs/media', 'SignController@storeMedia')->name('signs.storeMedia');
    Route::post('signs/ckmedia', 'SignController@storeCKEditorImages')->name('signs.storeCKEditorImages');
    Route::resource('signs', 'SignController');

    // Color
    Route::delete('colors/destroy', 'ColorController@massDestroy')->name('colors.massDestroy');
    Route::resource('colors', 'ColorController');

    // Course
    Route::delete('courses/destroy', 'CourseController@massDestroy')->name('courses.massDestroy');
    Route::post('courses/media', 'CourseController@storeMedia')->name('courses.storeMedia');
    Route::post('courses/ckmedia', 'CourseController@storeCKEditorImages')->name('courses.storeCKEditorImages');
    Route::resource('courses', 'CourseController');

    // Course Chapter
    Route::delete('course-chapters/destroy', 'CourseChapterController@massDestroy')->name('course-chapters.massDestroy');
    Route::resource('course-chapters', 'CourseChapterController');

    // Chapter Item
    Route::delete('chapter-items/destroy', 'ChapterItemController@massDestroy')->name('chapter-items.massDestroy');
    Route::resource('chapter-items', 'ChapterItemController');

    // Video
    Route::delete('videos/destroy', 'VideoController@massDestroy')->name('videos.massDestroy');
    Route::post('videos/media', 'VideoController@storeMedia')->name('videos.storeMedia');
    Route::post('videos/ckmedia', 'VideoController@storeCKEditorImages')->name('videos.storeCKEditorImages');
    Route::resource('videos', 'VideoController');

    // File
    Route::delete('files/destroy', 'FileController@massDestroy')->name('files.massDestroy');
    Route::post('files/media', 'FileController@storeMedia')->name('files.storeMedia');
    Route::post('files/ckmedia', 'FileController@storeCKEditorImages')->name('files.storeCKEditorImages');
    Route::resource('files', 'FileController');

    // Page
    Route::delete('pages/destroy', 'PageController@massDestroy')->name('pages.massDestroy');
    Route::post('pages/media', 'PageController@storeMedia')->name('pages.storeMedia');
    Route::post('pages/ckmedia', 'PageController@storeCKEditorImages')->name('pages.storeCKEditorImages');
    Route::resource('pages', 'PageController');

    // Test
    Route::delete('tests/destroy', 'TestController@massDestroy')->name('tests.massDestroy');
    Route::post('tests/media', 'TestController@storeMedia')->name('tests.storeMedia');
    Route::post('tests/ckmedia', 'TestController@storeCKEditorImages')->name('tests.storeCKEditorImages');
    Route::resource('tests', 'TestController');

    // Question
    Route::delete('questions/destroy', 'QuestionController@massDestroy')->name('questions.massDestroy');
    Route::post('questions/media', 'QuestionController@storeMedia')->name('questions.storeMedia');
    Route::post('questions/ckmedia', 'QuestionController@storeCKEditorImages')->name('questions.storeCKEditorImages');
    Route::resource('questions', 'QuestionController');

    // Answer
    Route::delete('answers/destroy', 'AnswerController@massDestroy')->name('answers.massDestroy');
    Route::resource('answers', 'AnswerController');

    // News
    Route::delete('news/destroy', 'NewsController@massDestroy')->name('news.massDestroy');
    Route::post('news/media', 'NewsController@storeMedia')->name('news.storeMedia');
    Route::post('news/ckmedia', 'NewsController@storeCKEditorImages')->name('news.storeCKEditorImages');
    Route::resource('news', 'NewsController');

    // Popup News
    Route::delete('popup-news/destroy', 'PopupNewsController@massDestroy')->name('popup-news.massDestroy');
    Route::resource('popup-news', 'PopupNewsController');

    // Game Available Items
    Route::delete('game-available-items/destroy', 'GameAvailableItemsController@massDestroy')->name('game-available-items.massDestroy');
    Route::resource('game-available-items', 'GameAvailableItemsController');

    // Passed Test
    Route::delete('passed-tests/destroy', 'PassedTestController@massDestroy')->name('passed-tests.massDestroy');
    Route::resource('passed-tests', 'PassedTestController');

    // Test Sign Color
    Route::delete('test-sign-colors/destroy', 'TestSignColorController@massDestroy')->name('test-sign-colors.massDestroy');
    Route::resource('test-sign-colors', 'TestSignColorController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');

app/Models/TestSignColor.php
<?php

namespace App\Models;

use \DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class TestSignColor extends Model
{
    use SoftDeletes;
    use HasFactory;

    public $table = 'test_sign_colors';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'course_id',
        'test_id',
        'sign_id',
        'color_id',
        'user_id',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function course()
    {
        return $this->belongsTo(Course::class, 'course_id');
    }

    public function test()
    {
        return $this->belongsTo(Test::class, 'test_id');
    }

    public function sign()
    {
        return $this->belongsTo(Sign::class, 'sign_id');
    }

    public function color()
    {
        return $this->belongsTo(Color::class, 'color_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/TestSignColorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyTestSignColorRequest;
use App\Http\Requests\StoreTestSignColorRequest;
use App\Http\Requests\UpdateTestSignColorRequest;
use App\Models\Color;
use App\Models\Course;
use App\Models\Sign;
use App\Models\Test;
use App\Models\TestSignColor;
use App\Models\User;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class TestSignColorController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('test_sign_color_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $testSignColors = TestSignColor::with(['course', 'test', 'sign', 'color', 'user'])->get();

        return view('admin.testSignColors.index', compact('testSignColors'));
    }

    public function create()
    {
        abort_if(Gate::denies('test_sign_color_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $courses = Course::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $tests = Test::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $signs = Sign::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $colors = Color::pluck('html_color', 'id')->prepend(trans('global.pleaseSelect'), '');

        $users = User::pluck('email', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.testSignColors.create', compact('colors', 'courses', 'signs', 'tests', 'users'));
    }

    public function store(StoreTestSignColorRequest $request)
    {
        $testSignColor = TestSignColor::create($request->all());

        return redirect()->route('admin.test-sign-colors.index');
    }

    public function edit(TestSignColor $testSignColor)
    {
        abort_if(Gate::denies('test_sign_color_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $courses = Course::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $tests = Test::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $signs = Sign::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $colors = Color::pluck('html_color', 'id')->prepend(trans('global.pleaseSelect'), '');

        $users = User::pluck('email', 'id')->prepend(trans('global.pleaseSelect'), '');

        $testSignColor->load('course', 'test', 'sign', 'color', 'user');

        return view('admin.testSignColors.edit', compact('colors', 'courses', 'signs', 'testSignColor', 'tests', 'users'));
    }

    public function update(UpdateTestSignColorRequest $request, TestSignColor $testSignColor)
    {
        $testSignColor->update($request->all());

        return redirect()->route('admin.test-sign-colors.index');
    }

    public function show(TestSignColor $testSignColor)
    {
        abort_if(Gate::denies('test_sign_color_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $testSignColor->load('course', 'test', 'sign', 'color', 'user');

        return view('admin.testSignColors.show', compact('testSignColor'));
    }

    public function destroy(TestSignColor $testSignColor)
    {
        abort_if(Gate::denies('test_sign_color_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $testSignColor->delete();

        return back();
    }

    public function massDestroy(MassDestroyTestSignColorRequest $request)
    {
        TestSignColor::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/testSignColors/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.testSignColor.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.test-sign-colors.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="course_id">{{ trans('cruds.testSignColor.fields.course') }}</label>
                <select class="form-control select2 {{ $errors->has('course') ? 'is-invalid' : '' }}" name="course_id" id="course_id">
                    @foreach($courses as $id => $entry)
                        <option value="{{ $id }}" {{ old('course_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('course'))
                    <div class="invalid-feedback">
                        {{ $errors->first('course') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.testSignColor.fields.course_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="test_id">{{ trans('cruds.testSignColor.fields.test') }}</label>
                <select class="form-control select2 {{ $errors->has('test') ? 'is-invalid' : '' }}" name="test_id" id="test_id">
                    @foreach($tests as $id => $entry)
                        <option value="{{ $id }}" {{ old('test_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('test'))
                    <div class="invalid-feedback">
                        {{ $errors->first('test') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.testSignColor.fields.test_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="sign_id">{{ trans('cruds.testSignColor.fields.sign') }}</label>
                <select class="form-control select2 {{ $errors->has('sign') ? 'is-invalid' : '' }}" name="sign_id" id="sign_id">
                    @foreach($signs as $id => $entry)
                        <option value="{{ $id }}" {{ old('sign_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('sign'))
                    <div class="invalid-feedback">
                        {{ $errors->first('sign') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.testSignColor.fields.sign_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="color_id">{{ trans('cruds.testSignColor.fields.color') }}</label>
                <select class="form-control select2 {{ $errors->has('color') ? 'is-invalid' : '' }}" name="color_id" id="color_id">
                    @foreach($colors as $id => $entry)
                        <option value="{{ $id }}" {{ old('color_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('color'))
                    <div class="invalid-feedback">
                        {{ $errors->first('color') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.testSignColor.fields.color_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="user_id">{{ trans('cruds.testSignColor.fields.user') }}</label>
                <select class="form-control select2 {{ $errors->has('user') ? 'is-invalid' : '' }}" name="user_id" id="user_id">
                    @foreach($users as $id => $entry)
                        <option value="{{ $id }}" {{ old('user_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('user'))
                    <div class="invalid-feedback">
                        {{ $errors->first('user') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.testSignColor.fields.user_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/testSignColors/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.testSignColor.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.test-sign-colors.update", [$testSignColor->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="course_id">{{ trans('cruds.testSignColor.fields.course') }}</label>
                <select class="form-control select2 {{ $errors->has('course') ? 'is-invalid' : '' }}" name="course_id" id="course_id">
                    @foreach($courses as $id => $entry)
                        <option value="{{ $id }}" {{ (old('course_id') ? old('course_id') : $testSignColor->course->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('course'))
                    <div class="invalid-feedback">
                        {{ $errors->first('course') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.testSignColor.fields.course_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="test_id">{{ trans('cruds.testSignColor.fields.test') }}</label>
                <select class="form-control select2 {{ $errors->has('test') ? 'is-invalid' : '' }}" name="test_id" id="test_id">
                    @foreach($tests as $id => $entry)
                        <option value="{{ $id }}" {{ (old('test_id') ? old('test_id') : $testSignColor->test->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('test'))
                    <div class="invalid-feedback">
                        {{ $errors->first('test') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.testSignColor.fields.test_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="sign_id">{{ trans('cruds.testSignColor.fields.sign') }}</label>
                <select class="form-control select2 {{ $errors->has('sign') ? 'is-invalid' : '' }}" name="sign_id" id="sign_id">
                    @foreach($signs as $id => $entry)
                        <option value="{{ $id }}" {{ (old('sign_id') ? old('sign_id') : $testSignColor->sign->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('sign'))
                    <div class="invalid-feedback">
                        {{ $errors->first('sign') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.testSignColor.fields.sign_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="color_id">{{ trans('cruds.testSignColor.fields.color') }}</label>
                <select class="form-control select2 {{ $errors->has('color') ? 'is-invalid' : '' }}" name="color_id" id="color_id">
                    @foreach($colors as $id => $entry)
                        <option value="{{ $id }}" {{ (old('color_id') ? old('color_id') : $testSignColor->color->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('color'))
                    <div class="invalid-feedback">
                        {{ $errors->first('color') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.testSignColor.fields.color_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="user_id">{{ trans('cruds.testSignColor.fields.user') }}</label>
                <select class="form-control select2 {{ $errors->has('user') ? 'is-invalid' : '' }}" name="user_id" id="user_id">
                    @foreach($users as $id => $entry)
                        <option value="{{ $id }}" {{ (old('user_id') ? old('user_id') : $testSignColor->user->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('user'))
                    <div class="invalid-feedback">
                        {{ $errors->first('user') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.testSignColor.fields.user_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/testSignColors/index.blade.php
@extends('layouts.admin')
@section('content')
@can('test_sign_color_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.test-sign-colors.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.testSignColor.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.testSignColor.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-TestSignColor">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.testSignColor.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.testSignColor.fields.course') }}
                        </th>
                        <th>
                            {{ trans('cruds.testSignColor.fields.test') }}
                        </th>
                        <th>
                            {{ trans('cruds.testSignColor.fields.sign') }}
                        </th>
                        <th>
                            {{ trans('cruds.testSignColor.fields.color') }}
                        </th>
                        <th>
                            {{ trans('cruds.testSignColor.fields.user') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($testSignColors as $key => $testSignColor)
                        <tr data-entry-id="{{ $testSignColor->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $testSignColor->id ?? '' }}
                            </td>
                            <td>
                                {{ $testSignColor->course->name ?? '' }}
                            </td>
                            <td>
                                {{ $testSignColor->test->name ?? '' }}
                            </td>
                            <td>
                                {{ $testSignColor->sign->name ?? '' }}
                            </td>
                            <td>
                                {{ $testSignColor->color->html_color ?? '' }}
                            </td>
                            <td>
                                {{ $testSignColor->user->email ?? '' }}
                            </td>
                            <td>
                                @can('test_sign_color_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.test-sign-colors.show', $testSignColor->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('test_sign_color_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.test-sign-colors.edit', $testSignColor->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('test_sign_color_delete')
                                    <form action="{{ route('admin.test-sign-colors.destroy', $testSignColor->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('test_sign_color_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.test-sign-colors.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-TestSignColor:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection