routes/web.php
    Route::get('/course/{course_id}/delete-chapter/{chapter_id}', 'ManageCourseController@deleteChapter');
    Route::post('/course/{course_id}/chapter-elements-order-update/{chapter_id}', 'ManageCourseController@chapterElementsOrderUpdate');
    Route::get('/course/{course_id}/chapter-order-edit', 'ManageCourseController@chapterOrderEdit');
    Route::post('/course/{course_id}/chapter-order-edit-update', 'ManageCourseController@chapterOrderEditUpdate');

    Route::get('/add-element/{course_id}/{chapter_id}', 'ManageChapterItemsController@addElement');
    Route::post('/add-element-store/{course_id}/{chapter_id}', 'ManageChapterItemsController@addElementStore');
    Route::get('/edit-element/{element_id}/{item_id}', 'ManageChapterItemsController@editElement');

    Route::get('/course/{course_id}/edit-element/{element_id}', 'ManageChapterItemsController@editElement');
    Route::post('/course/{course_id}/change-elem-name-update/{element_id}', 'ManageChapterItemsController@changeElemName');
    Route::get('/course/{course_id}/delete-element/{element_id}', 'ManageChapterItemsController@deleteElement');

    Route::post('/course/{course_id}/edit-video-update/{chapter_item_id}', 'ManageChapterItemsController@editVideoUpdate');
    Route::post('/course/{course_id}/add-file-store/{chapter_item_id}', 'ManageChapterItemsController@addFileStore');
    Route::get('/course/{course_id}/delete-file/{file_id}', 'ManageChapterItemsController@deleteFile');
    Route::post('/course/{course_id}/edit-page-update/{chapter_item_id}', 'ManageChapterItemsController@editPageUpdate');
    Route::post('/upload-page-media/ckeditor', 'ManageChapterItemsController@uploadCkeditorMedia')->name('upload-ckeditor-media');

    Route::get('/course/{course_id}/test/{test_id}/add-question-store', 'ManageChapterItemsController@addQuestionStore');
    Route::get('/course/{course_id}/delete-question/{question_id}', 'ManageChapterItemsController@deleteQuestion');
    Route::get('/course/{course_id}/question/{question_id}/add-answer-store', 'ManageChapterItemsController@addAnswerStore');
    Route::get('/course/{course_id}/question/{question_id}/delete-answer/{answer_id}', 'ManageChapterItemsController@deleteAnswer');
    Route::post('/course/{course}/edit-question-update/{question_id}', 'ManageChapterItemsController@editQuestionUpdate');

});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/media', 'UsersController@storeMedia')->name('users.storeMedia');
    Route::post('users/ckmedia', 'UsersController@storeCKEditorImages')->name('users.storeCKEditorImages');
    Route::resource('users', 'UsersController');

    // Course Elements
    Route::delete('course-elements/destroy', 'CourseElementsController@massDestroy')->name('course-elements.massDestroy');
    Route::post('course-elements/media', 'CourseElementsController@storeMedia')->name('course-elements.storeMedia');
    Route::post('course-elements/ckmedia', 'CourseElementsController@storeCKEditorImages')->name('course-elements.storeCKEditorImages');
    Route::resource('course-elements', 'CourseElementsController');

    // Course Category
    Route::delete('course-categories/destroy', 'CourseCategoryController@massDestroy')->name('course-categories.massDestroy');
    Route::resource('course-categories', 'CourseCategoryController');

    // Course Class
    Route::delete('course-classes/destroy', 'CourseClassController@massDestroy')->name('course-classes.massDestroy');
    Route::resource('course-classes', 'CourseClassController');

    // Game Background
    Route::delete('game-backgrounds/destroy', 'GameBackgroundController@massDestroy')->name('game-backgrounds.massDestroy');
    Route::post('game-backgrounds/media', 'GameBackgroundController@storeMedia')->name('game-backgrounds.storeMedia');
    Route::post('game-backgrounds/ckmedia', 'GameBackgroundController@storeCKEditorImages')->name('game-backgrounds.storeCKEditorImages');
    Route::resource('game-backgrounds', 'GameBackgroundController');

    // Station
    Route::delete('stations/destroy', 'StationController@massDestroy')->name('stations.massDestroy');
    Route::post('stations/media', 'StationController@storeMedia')->name('stations.storeMedia');
    Route::post('stations/ckmedia', 'StationController@storeCKEditorImages')->name('stations.storeCKEditorImages');
    Route::resource('stations', 'StationController');

    // Sign
    Route::delete('signs/destroy', 'SignController@massDestroy')->name('signs.massDestroy');
    Route::post('signs/media', 'SignController@storeMedia')->name('signs.storeMedia');
    Route::post('signs/ckmedia', 'SignController@storeCKEditorImages')->name('signs.storeCKEditorImages');
    Route::resource('signs', 'SignController');

    // Color
    Route::delete('colors/destroy', 'ColorController@massDestroy')->name('colors.massDestroy');
    Route::resource('colors', 'ColorController');

    // Course
    Route::delete('courses/destroy', 'CourseController@massDestroy')->name('courses.massDestroy');
    Route::post('courses/media', 'CourseController@storeMedia')->name('courses.storeMedia');
    Route::post('courses/ckmedia', 'CourseController@storeCKEditorImages')->name('courses.storeCKEditorImages');
    Route::resource('courses', 'CourseController');

    // Course Chapter
    Route::delete('course-chapters/destroy', 'CourseChapterController@massDestroy')->name('course-chapters.massDestroy');
    Route::resource('course-chapters', 'CourseChapterController');

    // Chapter Item
    Route::delete('chapter-items/destroy', 'ChapterItemController@massDestroy')->name('chapter-items.massDestroy');
    Route::resource('chapter-items', 'ChapterItemController');

    // Video
    Route::delete('videos/destroy', 'VideoController@massDestroy')->name('videos.massDestroy');
    Route::post('videos/media', 'VideoController@storeMedia')->name('videos.storeMedia');
    Route::post('videos/ckmedia', 'VideoController@storeCKEditorImages')->name('videos.storeCKEditorImages');
    Route::resource('videos', 'VideoController');

    // File
    Route::delete('files/destroy', 'FileController@massDestroy')->name('files.massDestroy');
    Route::post('files/media', 'FileController@storeMedia')->name('files.storeMedia');
    Route::post('files/ckmedia', 'FileController@storeCKEditorImages')->name('files.storeCKEditorImages');
    Route::resource('files', 'FileController');

    // Page
    Route::delete('pages/destroy', 'PageController@massDestroy')->name('pages.massDestroy');
    Route::post('pages/media', 'PageController@storeMedia')->name('pages.storeMedia');
    Route::post('pages/ckmedia', 'PageController@storeCKEditorImages')->name('pages.storeCKEditorImages');
    Route::resource('pages', 'PageController');

    // Test
    Route::delete('tests/destroy', 'TestController@massDestroy')->name('tests.massDestroy');
    Route::post('tests/media', 'TestController@storeMedia')->name('tests.storeMedia');
    Route::post('tests/ckmedia', 'TestController@storeCKEditorImages')->name('tests.storeCKEditorImages');
    Route::resource('tests', 'TestController');

    // Question
    Route::delete('questions/destroy', 'QuestionController@massDestroy')->name('questions.massDestroy');
    Route::post('questions/media', 'QuestionController@storeMedia')->name('questions.storeMedia');
    Route::post('questions/ckmedia', 'QuestionController@storeCKEditorImages')->name('questions.storeCKEditorImages');
    Route::resource('questions', 'QuestionController');

    // Answer
    Route::delete('answers/destroy', 'AnswerController@massDestroy')->name('answers.massDestroy');
    Route::resource('answers', 'AnswerController');

    // News
    Route::delete('news/destroy', 'NewsController@massDestroy')->name('news.massDestroy');
    Route::post('news/media', 'NewsController@storeMedia')->name('news.storeMedia');
    Route::post('news/ckmedia', 'NewsController@storeCKEditorImages')->name('news.storeCKEditorImages');
    Route::resource('news', 'NewsController');

    // Popup News
    Route::delete('popup-news/destroy', 'PopupNewsController@massDestroy')->name('popup-news.massDestroy');
    Route::resource('popup-news', 'PopupNewsController');

    // Game Available Items
    Route::delete('game-available-items/destroy', 'GameAvailableItemsController@massDestroy')->name('game-available-items.massDestroy');
    Route::resource('game-available-items', 'GameAvailableItemsController');

    // Passed Test
    Route::delete('passed-tests/destroy', 'PassedTestController@massDestroy')->name('passed-tests.massDestroy');
    Route::resource('passed-tests', 'PassedTestController');

    // Test Sign Color
    Route::delete('test-sign-colors/destroy', 'TestSignColorController@massDestroy')->name('test-sign-colors.massDestroy');
    Route::resource('test-sign-colors', 'TestSignColorController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');

app/Http/Controllers/Admin/CourseClassController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyCourseClassRequest;
use App\Http\Requests\StoreCourseClassRequest;
use App\Http\Requests\UpdateCourseClassRequest;
use App\Models\CourseClass;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class CourseClassController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('course_class_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $courseClasses = CourseClass::all();

        return view('admin.courseClasses.index', compact('courseClasses'));
    }

    public function create()
    {
        abort_if(Gate::denies('course_class_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.courseClasses.create');
    }

    public function store(StoreCourseClassRequest $request)
    {
        $courseClass = CourseClass::create($request->all());

        return redirect()->route('admin.course-classes.index');
    }

    public function edit(CourseClass $courseClass)
    {
        abort_if(Gate::denies('course_class_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.courseClasses.edit', compact('courseClass'));
    }

    public function update(UpdateCourseClassRequest $request, CourseClass $courseClass)
    {
        $courseClass->update($request->all());

        return redirect()->route('admin.course-classes.index');
    }

    public function show(CourseClass $courseClass)
    {
        abort_if(Gate::denies('course_class_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.courseClasses.show', compact('courseClass'));
    }

    public function destroy(CourseClass $courseClass)
    {
        abort_if(Gate::denies('course_class_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $courseClass->delete();

        return back();
    }

    public function massDestroy(MassDestroyCourseClassRequest $request)
    {
        CourseClass::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/courseClasses/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.courseClass.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.course-classes.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="class">{{ trans('cruds.courseClass.fields.class') }}</label>
                <input class="form-control {{ $errors->has('class') ? 'is-invalid' : '' }}" type="text" name="class" id="class" value="{{ old('class', '') }}" required>
                @if($errors->has('class'))
                    <div class="invalid-feedback">
                        {{ $errors->first('class') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.courseClass.fields.class_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/courseClasses/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.courseClass.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.course-classes.update", [$courseClass->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="class">{{ trans('cruds.courseClass.fields.class') }}</label>
                <input class="form-control {{ $errors->has('class') ? 'is-invalid' : '' }}" type="text" name="class" id="class" value="{{ old('class', $courseClass->class) }}" required>
                @if($errors->has('class'))
                    <div class="invalid-feedback">
                        {{ $errors->first('class') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.courseClass.fields.class_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/courseClasses/index.blade.php
@extends('layouts.admin')
@section('content')
@can('course_class_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.course-classes.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.courseClass.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.courseClass.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-CourseClass">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.courseClass.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.courseClass.fields.class') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($courseClasses as $key => $courseClass)
                        <tr data-entry-id="{{ $courseClass->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $courseClass->id ?? '' }}
                            </td>
                            <td>
                                {{ $courseClass->class ?? '' }}
                            </td>
                            <td>
                                @can('course_class_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.course-classes.show', $courseClass->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('course_class_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.course-classes.edit', $courseClass->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('course_class_delete')
                                    <form action="{{ route('admin.course-classes.destroy', $courseClass->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('course_class_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.course-classes.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-CourseClass:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/courseClasses/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.courseClass.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.course-classes.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.courseClass.fields.id') }}
                        </th>
                        <td>
                            {{ $courseClass->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.courseClass.fields.class') }}
                        </th>
                        <td>
                            {{ $courseClass->class }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.course-classes.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection